// starrail_chars.js
// スタレキャラクター・バージョン共通マスターデータ
//
// 使い方:
//   TiersList02 (運命別) : starrailChars を path でフィルタしてタブ表示
//   TiersList03 (属性別) : starrailChars を element でフィルタしてタブ表示
//   StarRailCheck        : starrailChars (chara タブ) + starrailVersions (version タブ) を使用
//
// path:    yuetu=愉悦, songo=存護, junsyu=巡狩, tie=知恵, kyomu=虚無,
//          kaimetsu=壊滅, tyouwa=調和, houjou=豊穣, kioku=記憶, null=タブ非対象
// element: butsuri=物理, hi=炎, koori=氷, kaze=風, kaminari=雷,
//          kyosuu=虚数, ryoushi=量子, null=タブ非対象

// ===== キャラクターデータ =====
export const starrailChars = [

  { icon: "syu5.png",       path: "yuetu",    element: "kaminari" },
  { icon: "sei5.png",       path: "yuetu",    element: "kaminari" },
  { icon: "ginro2.png",     path: "yuetu",    element: "kyosuu"   },
  { icon: "jin2.png",       path: "kyomu",    element: "hi"       },
  { icon: "sutera.png",     path: null,       element: null       },
  { icon: "sinazu.png",     path: "junsyu",   element: "kaminari" },
  { icon: "hiei.png",       path: "yuetu",    element: "butsuri"  },
  { icon: "koukou.png",     path: "yuetu",    element: "butsuri"  },
  { icon: "hibana.png",     path: "yuetu",    element: "hi"       },
  { icon: "daria.png",      path: "kyomu",    element: "hi"       },
  { icon: "kyurene.png",    path: "kioku",    element: "koori"    },
  { icon: "tankou2.png",    path: "songo",    element: "butsuri"  },
  { icon: "nagayatuki.png", path: "kioku",    element: "koori"    },
  { icon: "keryu.png",      path: "tyouwa",   element: "kaze"     },
  { icon: "seirensu.png",   path: "kyomu",    element: "butsuri"  },
  { icon: "fainon.png",     path: "kaimetsu", element: "butsuri"  },
  { icon: "atya.png",       path: "junsyu",   element: "ryoushi"  },
  { icon: "seiba.png",      path: "kaimetsu", element: "kaze"     },
  { icon: "saferu.png",     path: "kyomu",    element: "ryoushi"  },
  { icon: "hiansi.png",     path: "kioku",    element: "kaze"     },
  { icon: "anaikusu.png",   path: "tie",      element: "kaze"     },
  { icon: "kyasuto.png",    path: "kioku",    element: "ryoushi"  },
  { icon: "modis.png",      path: "kaimetsu", element: "kyosuu"   },
  { icon: "toribi.png",     path: "tyouwa",   element: "ryoushi"  },
  { icon: "syu4.png",       path: "kioku",    element: "koori"    },
  { icon: "sei4.png",       path: "kioku",    element: "koori"    },
  { icon: "aguraia.png",    path: "kioku",    element: "kaminari" },
  { icon: "heltamama.png",  path: "tie",      element: "koori"    },
  { icon: "newteiun.png",   path: "kyomu",    element: "hi"       },
  { icon: "sunday.png",     path: "tyouwa",   element: "kyosuu"   },
  { icon: "ranpa.png",      path: "tie",      element: "kyosuu"   },
  { icon: "moze.png",       path: "junsyu",   element: "kaminari" },
  { icon: "reisa.png",      path: "houjou",   element: "hi"       },
  { icon: "hisyo.png",      path: "junsyu",   element: "kaze"     },
  { icon: "nanoka2.png",    path: "junsyu",   element: "kyosuu"   },
  { icon: "syokyu.png",     path: "kyomu",    element: "hi"       },
  { icon: "unri.png",       path: "kaimetsu", element: "butsuri"  },
  { icon: "syu3.png",       path: "tyouwa",   element: "kyosuu"   },
  { icon: "sei3.png",       path: "tyouwa",   element: "kyosuu"   },
  { icon: "jeido.png",      path: "tie",      element: "ryoushi"  },
  { icon: "hotaru.png",     path: "kaimetsu", element: "hi"       },
  { icon: "boothill.png",   path: "junsyu",   element: "butsuri"  },
  { icon: "robin.png",      path: "tyouwa",   element: "butsuri"  },
  { icon: "gyaraga.png",    path: "houjou",   element: "hi"       },
  { icon: "aben.png",       path: "songo",    element: "kyosuu"   },
  { icon: "yomi.png",       path: "kyomu",    element: "kaminari" },
  { icon: "misia.png",      path: "kaimetsu", element: "koori"    },
  { icon: "hanabi.png",     path: "tyouwa",   element: "ryoushi"  },
  { icon: "swan.png",       path: "kyomu",    element: "kaze"     },
  { icon: "setui.png",      path: "kaimetsu", element: "ryoushi"  },
  { icon: "reisio.png",     path: "junsyu",   element: "kyosuu"   },
  { icon: "ruanmama.png",   path: "tyouwa",   element: "koori"    },
  { icon: "kana.png",       path: "tyouwa",   element: "butsuri"  },
  { icon: "arujen.png",     path: "tie",      element: "butsuri"  },
  { icon: "fofo.png",       path: "houjou",   element: "kaze"     },
  { icon: "ketya.png",      path: "kyomu",    element: "hi"       },
  { icon: "topazu.png",     path: "junsyu",   element: "hi"       },
  { icon: "keiryu.png",     path: "kaimetsu", element: "koori"    },
  { icon: "rinkusu.png",    path: "houjou",   element: "ryoushi"  },
  { icon: "ingetsu.png",    path: "kaimetsu", element: "kyosuu"   },
  { icon: "hugen.png",      path: "songo",    element: "ryoushi"  },
  { icon: "ruka.png",       path: "kyomu",    element: "butsuri"  },
  { icon: "kahuka.png",     path: "kyomu",    element: "kaminari" },
  { icon: "jin.png",        path: "kaimetsu", element: "kaze"     },
  { icon: "gyoku.png",      path: "tyouwa",   element: "kyosuu"   },
  { icon: "rasetu.png",     path: "houjou",   element: "kyosuu"   },
  { icon: "ginro.png",      path: "kyomu",    element: "ryoushi"  },
  { icon: "byakuro.png",    path: "houjou",   element: "kaminari" },
  { icon: "genkyo.png",     path: "junsyu",   element: "koori"    },
  { icon: "susyo.png",      path: "junsyu",   element: "butsuri"  },
  { icon: "keigen.png",     path: "tie",      element: "kaminari" },
  { icon: "teiun.png",      path: "tyouwa",   element: "kaminari" },
  { icon: "seijaku.png",    path: "tie",      element: "ryoushi"  },
  { icon: "syu2.png",       path: "songo",    element: "hi"       },
  { icon: "sei2.png",       path: "songo",    element: "hi"       },
  { icon: "hukku.png",      path: "kaimetsu", element: "hi"       },
  { icon: "sanpo.png",      path: "kyomu",    element: "kaze"     },
  { icon: "kurara.png",     path: "kaimetsu", element: "butsuri"  },
  { icon: "pera.png",       path: "kyomu",    element: "koori"    },
  { icon: "natasya.png",    path: "houjou",   element: "butsuri"  },
  { icon: "jepado.png",     path: "songo",    element: "koori"    },
  { icon: "sebaru.png",     path: "tie",      element: "kaminari" },
  { icon: "zere.png",       path: "junsyu",   element: "ryoushi"  },
  { icon: "buronya.png",    path: "tyouwa",   element: "kaze"     },
  { icon: "helta.png",      path: "tie",      element: "koori"    },
  { icon: "aster.png",      path: "tyouwa",   element: "hi"       },
  { icon: "aran.png",       path: "kaimetsu", element: "kaminari" },
  { icon: "velto.png",      path: "kyomu",    element: "kyosuu"   },
  { icon: "himeko.png",     path: "tie",      element: "hi"       },
  { icon: "tankou.png",     path: "junsyu",   element: "kaze"     },
  { icon: "nanoka.png",     path: "songo",    element: "koori"    },
  { icon: "syu1.png",       path: "kaimetsu", element: "butsuri"  },
  { icon: "sei1.png",       path: "kaimetsu", element: "butsuri"  },

];

// ===== バージョン画像データ (StarRailCheck用) =====
export const starrailVersions = [
  "4_2.png",
  "4_1.png",
  "4_0.png",
  "3_8.png",
  "3_7.png",
  "3_6.png",
  "3_5.png",
  "3_4.png",
  "3_3.png",
  "3_2.png",
  "3_1.png",
  "3_0.png",
  "2_7.png",
  "2_6.png",
  "2_5.png",
  "2_4.png",
  "2_3.png",
  "2_2.png",
  "2_1.png",
  "2_0.png",
  "1_6.png",
  "1_5.png",
  "1_4.png",
  "1_3.png",
  "1_2.png",
  "1_1.png",
  "1_0.png",
];
