// genshin_chars.js
// 原神キャラクター・バージョン共通マスターデータ
//
// 使い方:
//   TiersList / Mirishira : genshinChars を element でフィルタしてタブ表示
//   GenshinCheck          : genshinChars (chara タブ) + genshinVersions (version タブ) を使用
//
// element: hi=炎, mizu=水, koori=氷, kaminari=雷, kusa=草, kaze=風, iwa=岩, null=元素タブ非対象

// ===== キャラクターデータ =====
export const genshinChars = [

  { name: "プルーネ",       icon: "puruune.png",          element: "kaze"      },
  { name: "リンネア",       icon: "linnea.png",           element: "iwa"      },
  { name: "ローエン",       icon: "rooen.png",            element: "koori"    },
  { name: "イルーガ",       icon: "iruga.png",            element: "iwa"      },
  { name: "茲白",           icon: "shihaku.png",          element: "iwa"      },
  { name: "コロンビーナ",   icon: "shojo.png",            element: "mizu"     },
  { name: "傀儡",           icon: "kairai.png",           element: null       },
  { name: "ヤフォダ",       icon: "yafoda.png",           element: "kaze"     },
  { name: "ニコ",           icon: "niko.png",             element: "hi"       },
  { name: "アリス",         icon: "arisu.png",            element: "hi"       },
  { name: "ファルカ",       icon: "faruka.png",           element: "kaze"     },
  { name: "ドゥリン",       icon: "dorin.png",            element: "hi"       },
  { name: "ネフェル",       icon: "neferu.png",           element: "kusa"     },
  { name: "ラウマ",         icon: "rauma.png",            element: "kusa"     },
  { name: "フリンズ",       icon: "hurinzu.png",          element: "kaminari" },
  { name: "アイノ",         icon: "aino.png",             element: "mizu"     },
  { name: "イネファ",       icon: "inefa.png",            element: "kaminari" },
  { name: "スカーク",       icon: "skaku.png",            element: "koori"    },
  { name: "ダリア",         icon: "daria.png",            element: "mizu"     },
  { name: "エスコフィエ",   icon: "esuko.png",            element: "koori"    },
  { name: "イファ",         icon: "ifa.png",              element: "kaze"     },
  { name: "ヴァレサ",       icon: "baresa.png",           element: "kaminari" },
  { name: "イアンサ",       icon: "Iansan.png",           element: "kaminari" },
  { name: "夢見月瑞希",     icon: "mizuki.png",           element: "kaze"     },
  { name: "藍硯",           icon: "ranyan.png",           element: "kaze"     },
  { name: "オロルン",       icon: "oruron.png",           element: "kaminari" },
  { name: "シトラリ",       icon: "sitorari.png",         element: "koori"    },
  { name: "マーヴィカ",     icon: "Mavuika.png",          element: "hi"       },
  { name: "シロネン",       icon: "sironen.png",          element: "iwa"      },
  { name: "チャスカ",       icon: "Chasca.png",           element: "kaze"     },
  { name: "キィニチ",       icon: "Kinich.png",           element: "kusa"     },
  { name: "カチーナ",       icon: "Kachina.png",          element: "iwa"      },
  { name: "ムアラニ",       icon: "Mualani.png",          element: "mizu"     },
  { name: "エミリエ",       icon: "Emilie.png",           element: "kusa"     },
  { name: "シグウィン",     icon: "Sigewinne.png",        element: "mizu"     },
  { name: "クロリンデ",     icon: "Clorinde.png",         element: "kaminari" },
  { name: "セトス",         icon: "Sethos.png",           element: "kaminari" },
  { name: "アルレッキーノ", icon: "Arlecchino.png",       element: "hi"       },
  { name: "千織",           icon: "Chiori.png",           element: "iwa"      },
  { name: "嘉明",           icon: "Gaming.png",           element: "hi"       },
  { name: "閑雲",           icon: "Xianyun.png",          element: "kaze"     },
  { name: "シュヴルーズ",   icon: "Chevreuse.png",        element: "hi"       },
  { name: "ナヴィア",       icon: "Navia.png",            element: "iwa"      },
  { name: "シャルロット",   icon: "Charlotte.png",        element: "koori"    },
  { name: "フリーナ",       icon: "Furina.png",           element: "mizu"     },
  { name: "ヌヴィレット",   icon: "Neuvillette.png",      element: "mizu"     },
  { name: "リオセスリ",     icon: "Wriothesley.png",      element: "koori"    },
  { name: "フレミネ",       icon: "Freminet.png",         element: "koori"    },
  { name: "リネ",           icon: "Lyney.png",            element: "hi"       },
  { name: "リネット",       icon: "Lynette.png",          element: "kaze"     },
  { name: "綺良々",         icon: "Kirara.png",           element: "kusa"     },
  { name: "カーヴェ",       icon: "Kaveh.png",            element: "kusa"     },
  { name: "白朮",           icon: "Baizhu.png",           element: "kusa"     },
  { name: "ミカ",           icon: "Mika.png",             element: "koori"    },
  { name: "ディシア",       icon: "Dehya.png",            element: "hi"       },
  { name: "アルハイゼン",   icon: "Alhaitham.png",        element: "kusa"     },
  { name: "ヨォーヨ",       icon: "Yaoyao.png",           element: "kusa"     },
  { name: "放浪者",         icon: "Scaramouche.png",      element: "kaze"     },
  { name: "ファルザン",     icon: "Faruzan.png",          element: "kaze"     },
  { name: "レイラ",         icon: "Layla.png",            element: "koori"    },
  { name: "ナヒーダ",       icon: "Nahida.png",           element: "kusa"     },
  { name: "ニィロウ",       icon: "Nilou.png",            element: "mizu"     },
  { name: "キャンディス",   icon: "Candace.png",          element: "mizu"     },
  { name: "セノ",           icon: "Cyno.png",             element: "kaminari" },
  { name: "ドリー",         icon: "Dori.png",             element: "kaminari" },
  { name: "コレイ",         icon: "Collei.png",           element: "kusa"     },
  { name: "ティナリ",       icon: "Tighnari.png",         element: "kusa"     },
  { name: "鹿野院平蔵",     icon: "Heizou.png",           element: "kaze"     },
  { name: "久岐忍",         icon: "KukiShinobu.png",      element: "kaminari" },
  { name: "夜蘭",           icon: "Yelan.png",            element: "mizu"     },
  { name: "神里綾人",       icon: "KamisatoAyato.png",    element: "mizu"     },
  { name: "八重神子",       icon: "YaeMiko.png",          element: "kaminari" },
  { name: "雲菫",           icon: "YunJin.png",           element: "iwa"      },
  { name: "申鶴",           icon: "Shenhe.png",           element: "koori"    },
  { name: "荒瀧一斗",       icon: "AratakiItto.png",      element: "iwa"      },
  { name: "ゴロー",         icon: "Gorou.png",            element: "iwa"      },
  { name: "トーマ",         icon: "Thoma.png",            element: "hi"       },
  { name: "珊瑚宮心海",     icon: "Kokomi.png",           element: "mizu"     },
  { name: "九条裟羅",       icon: "KujouSara.png",        element: "kaminari" },
  { name: "雷電将軍",       icon: "Raiden.png",           element: "kaminari" },
  { name: "早柚",           icon: "Sayu.png",             element: "kaze"     },
  { name: "宵宮",           icon: "Yoimiya.png",          element: "hi"       },
  { name: "神里綾華",       icon: "AyakaKamisato.png",    element: "koori"    },
  { name: "楓原万葉",       icon: "KazuhaKaedehara.png",  element: "kaze"     },
  { name: "エウルア",       icon: "Eula.png",             element: "koori"    },
  { name: "煙緋",           icon: "YanFei.png",           element: "hi"       },
  { name: "ロサリア",       icon: "rosaria.png",          element: "koori"    },
  { name: "胡桃",           icon: "Hutao.png",            element: "hi"       },
  { name: "魈",             icon: "Xiao.png",             element: "kaze"     },
  { name: "甘雨",           icon: "Ganyu.png",            element: "koori"    },
  { name: "アルベド",       icon: "Albedo.png",           element: "iwa"      },
  { name: "鍾離",           icon: "Zhongli.png",          element: "iwa"      },
  { name: "辛炎",           icon: "Xinyan.png",           element: "hi"       },
  { name: "タルタリヤ",     icon: "Tartaglia.png",        element: "mizu"     },
  { name: "ディオナ",       icon: "Diona.png",            element: "koori"    },
  { name: "クレー",         icon: "Klee.png",             element: "hi"       },
  { name: "七七",           icon: "Qiqi.png",             element: "koori"    },
  { name: "刻晴",           icon: "Keqing.png",           element: "kaminari" },
  { name: "凝光",           icon: "Ningguang.png",        element: "iwa"      },
  { name: "香菱",           icon: "Xiangling.png",        element: "hi"       },
  { name: "行秋",           icon: "Xingqiu.png",          element: "mizu"     },
  { name: "重雲",           icon: "Chongyun.png",         element: "koori"    },
  { name: "北斗",           icon: "Beidou.png",           element: "kaminari" },
  { name: "ウェンティ",     icon: "Venti.png",            element: "kaze"     },
  { name: "ディルック",     icon: "Diluc.png",            element: "hi"       },
  { name: "モナ",           icon: "Mona.png",             element: "mizu"     },
  { name: "ジン",           icon: "Jean.png",             element: "kaze"     },
  { name: "レザー",         icon: "Razor.png",            element: "kaminari" },
  { name: "ノエル",         icon: "Noelle.png",           element: "iwa"      },
  { name: "バーバラ",       icon: "barbara.png",          element: "mizu"     },
  { name: "フィッシュル",   icon: "Fischl.png",           element: "kaminari" },
  { name: "ベネット",       icon: "Bennett.png",          element: "hi"       },
  { name: "スクロース",     icon: "Sucrose.png",          element: "kaze"     },
  { name: "リサ",           icon: "Lisa.png",             element: "kaminari" },
  { name: "ガイア",         icon: "Kaeya.png",            element: "koori"    },
  { name: "アンバー",       icon: "amber.png",            element: "hi"       },
  { name: "ホタル",         icon: "hotaru.png",           element: null       },
  { name: "ソラ",           icon: "sora.png",             element: null       },
  { name: "アーロイ",       icon: "aroi.png",             element: "koori"    },

];

// ===== バージョン画像データ (GenshinCheck用) =====
export const genshinVersions = [
  "luna6.png",
  "luna5.png",
  "luna4.png",
  "luna3.png",
  "luna2.png",
  "luna1.png",
  "5_8.png",
  "5_7.png",
  "5_6.png",
  "5_5.png",
  "5_4.png",
  "5_3.png",
  "5_2.png",
  "5_1.png",
  "5_0.png",
  "4_8.png",
  "4_7.png",
  "4_6.png",
  "4_5.png",
  "4_4.png",
  "4_3.png",
  "4_2.png",
  "4_1.png",
  "4_0.png",
  "3_8.png",
  "3_7.png",
  "3_6.png",
  "3_5.png",
  "3_4.png",
  "3_3.png",
  "3_2.png",
  "3_1.png",
  "3_0.png",
  "2_8.png",
  "2_7.png",
  "2_6.png",
  "2_5.png",
  "2_4.png",
  "2_3.png",
  "2_2.png",
  "2_1.png",
  "2_0.png",
  "1_6.png",
  "1_5.png",
  "1_4.png",
  "1_3.png",
  "1_2.png",
  "1_1.png",
  "1_0.png",
];
