// genshin_chars.js
// 原神キャラクター・バージョン共通マスターデータ
//
// 使い方:
//   TiersList / Mirishira : genshinChars を element でフィルタしてタブ表示
//   GenshinCheck          : genshinChars (chara タブ) + genshinVersions (version タブ) を使用
//
// element: hi=炎, mizu=水, koori=氷, kaminari=雷, kusa=草, kaze=風, iwa=岩, null=元素タブ非対象
// nation:  99_SharedImage/01_Genshin/country/ にある国画像のファイル名(拡張子なし)をそのまま使う。
//          Mondstadt, Liyue, Inazuma, Sumeru, Fontaine, Natlan, Snezhnaya, NodKrai
//          null=不明/未定(仮入力・要確認)
//          ※ AIによる暫定入力。特に自信度が低いキャラはnullのままにしてあるので、
//            国別ランキングを作る前に全件見直すこと。

// ===== キャラクターデータ =====
export const genshinChars = [

  { name: "ダニカ",           icon: "ダニカ.png",           element: "kaminari", nation: "Snezhnaya" },
  { name: "ノイ",             icon: "ノイ.png",             element: null,       nation: "Snezhnaya" },
  { name: "ミティヤ",         icon: "ミティヤ.png",         element: "kaminari", nation: "Snezhnaya" },
  { name: "バレリー",         icon: "バレリー.png",         element: "kaminari", nation: "Snezhnaya" },
  { name: "アナスターシャ",   icon: "アナスターシャ.png",   element: "koori",    nation: "Snezhnaya" },
  { name: "ヴォジャニーツァ", icon: "ヴォジャニーツァ.png", element: "mizu",     nation: "Snezhnaya" },
  { name: "オデット",         icon: "オデット.png",         element: "koori",    nation: "Snezhnaya" },
  { name: "ヴェスナ",         icon: "ヴェスナ.png",         element: "kaze",     nation: "Snezhnaya" },
  { name: "アリョーシャ",     icon: "アリョーシャ.png",     element: "kaminari", nation: "Snezhnaya" },
  { name: "サンドローネ",     icon: "kairai.png",           element: "koori",    nation: "Snezhnaya" },
  { name: "プルーネ",         icon: "puruune.png",          element: "kaze",     nation: "Mondstadt" },
  { name: "リンネア",         icon: "linnea.png",           element: "iwa",      nation: "NodKrai" },
  { name: "ローエン",         icon: "rooen.png",            element: "koori",    nation: "Mondstadt" },
  { name: "イルーガ",         icon: "iruga.png",            element: "iwa",      nation: "NodKrai" },
  { name: "茲白",             icon: "shihaku.png",          element: "iwa",      nation: "Liyue" },
  { name: "コロンビーナ",     icon: "shojo.png",            element: "mizu",     nation: "NodKrai" },
  { name: "ヤフォダ",         icon: "yafoda.png",           element: "kaze",     nation: "NodKrai" },
  { name: "ニコ",             icon: "niko.png",             element: "hi",       nation: null },
  { name: "アリス",           icon: "arisu.png",            element: "hi",       nation: null },
  { name: "ファルカ",         icon: "faruka.png",           element: "kaze",     nation: "Mondstadt" },
  { name: "ドゥリン",         icon: "dorin.png",            element: "hi",       nation: "Mondstadt" },
  { name: "ネフェル",         icon: "neferu.png",           element: "kusa",     nation: "NodKrai" },
  { name: "ラウマ",           icon: "rauma.png",            element: "kusa",     nation: "NodKrai" },
  { name: "フリンズ",         icon: "hurinzu.png",          element: "kaminari", nation: "NodKrai" },
  { name: "アイノ",           icon: "aino.png",             element: "mizu",     nation: "NodKrai" },
  { name: "イネファ",         icon: "inefa.png",            element: "kaminari", nation: "NodKrai" },
  { name: "スカーク",         icon: "skaku.png",            element: "koori",    nation: null },
  { name: "ダリア",           icon: "daria.png",            element: "mizu",     nation: "Mondstadt" },
  { name: "エスコフィエ",     icon: "esuko.png",            element: "koori",    nation: "Fontaine" },
  { name: "イファ",           icon: "ifa.png",              element: "kaze",     nation: "Natlan" },
  { name: "ヴァレサ",         icon: "baresa.png",           element: "kaminari", nation: "Natlan" },
  { name: "イアンサ",         icon: "Iansan.png",           element: "kaminari", nation: "Natlan" },
  { name: "夢見月瑞希",       icon: "mizuki.png",           element: "kaze",     nation: "Inazuma" },
  { name: "藍硯",             icon: "ranyan.png",           element: "kaze",     nation: "Liyue" },
  { name: "オロルン",         icon: "oruron.png",           element: "kaminari", nation: "Natlan" },
  { name: "シトラリ",         icon: "sitorari.png",         element: "koori",    nation: "Natlan" },
  { name: "マーヴィカ",       icon: "Mavuika.png",          element: "hi",       nation: "Natlan" },
  { name: "シロネン",         icon: "sironen.png",          element: "iwa",      nation: "Natlan" },
  { name: "チャスカ",         icon: "Chasca.png",           element: "kaze",     nation: "Natlan" },
  { name: "キィニチ",         icon: "Kinich.png",           element: "kusa",     nation: "Natlan" },
  { name: "カチーナ",         icon: "Kachina.png",          element: "iwa",      nation: "Natlan" },
  { name: "ムアラニ",         icon: "Mualani.png",          element: "mizu",     nation: "Natlan" },
  { name: "エミリエ",         icon: "Emilie.png",           element: "kusa",     nation: "Fontaine" },
  { name: "シグウィン",       icon: "Sigewinne.png",        element: "mizu",     nation: "Fontaine" },
  { name: "クロリンデ",       icon: "Clorinde.png",         element: "kaminari", nation: "Fontaine" },
  { name: "セトス",           icon: "Sethos.png",           element: "kaminari", nation: "Sumeru" },
  { name: "アルレッキーノ",   icon: "Arlecchino.png",       element: "hi",       nation: "Snezhnaya" },
  { name: "千織",             icon: "Chiori.png",           element: "iwa",      nation: "Inazuma" },
  { name: "嘉明",             icon: "Gaming.png",           element: "hi",       nation: "Liyue" },
  { name: "閑雲",             icon: "Xianyun.png",          element: "kaze",     nation: "Liyue" },
  { name: "シュヴルーズ",     icon: "Chevreuse.png",        element: "hi",       nation: "Fontaine" },
  { name: "ナヴィア",         icon: "Navia.png",            element: "iwa",      nation: "Fontaine" },
  { name: "シャルロット",     icon: "Charlotte.png",        element: "koori",    nation: "Fontaine" },
  { name: "フリーナ",         icon: "Furina.png",           element: "mizu",     nation: "Fontaine" },
  { name: "ヌヴィレット",     icon: "Neuvillette.png",      element: "mizu",     nation: "Fontaine" },
  { name: "リオセスリ",       icon: "Wriothesley.png",      element: "koori",    nation: "Fontaine" },
  { name: "フレミネ",         icon: "Freminet.png",         element: "koori",    nation: "Fontaine" },
  { name: "リネ",             icon: "Lyney.png",            element: "hi",       nation: "Fontaine" },
  { name: "リネット",         icon: "Lynette.png",          element: "kaze",     nation: "Fontaine" },
  { name: "綺良々",           icon: "Kirara.png",           element: "kusa",     nation: "Inazuma" },
  { name: "カーヴェ",         icon: "Kaveh.png",            element: "kusa",     nation: "Sumeru" },
  { name: "白朮",             icon: "Baizhu.png",           element: "kusa",     nation: "Liyue" },
  { name: "ミカ",             icon: "Mika.png",             element: "koori",    nation: "Mondstadt" },
  { name: "ディシア",         icon: "Dehya.png",            element: "hi",       nation: "Sumeru" },
  { name: "アルハイゼン",     icon: "Alhaitham.png",        element: "kusa",     nation: "Sumeru" },
  { name: "ヨォーヨ",         icon: "Yaoyao.png",           element: "kusa",     nation: "Liyue" },
  { name: "放浪者",           icon: "Scaramouche.png",      element: "kaze",     nation: "Sumeru" },
  { name: "ファルザン",       icon: "Faruzan.png",          element: "kaze",     nation: "Sumeru" },
  { name: "レイラ",           icon: "Layla.png",            element: "koori",    nation: "Sumeru" },
  { name: "ナヒーダ",         icon: "Nahida.png",           element: "kusa",     nation: "Sumeru" },
  { name: "ニィロウ",         icon: "Nilou.png",            element: "mizu",     nation: "Sumeru" },
  { name: "キャンディス",     icon: "Candace.png",          element: "mizu",     nation: "Sumeru" },
  { name: "セノ",             icon: "Cyno.png",             element: "kaminari", nation: "Sumeru" },
  { name: "ドリー",           icon: "Dori.png",             element: "kaminari", nation: "Sumeru" },
  { name: "コレイ",           icon: "Collei.png",           element: "kusa",     nation: "Sumeru" },
  { name: "ティナリ",         icon: "Tighnari.png",         element: "kusa",     nation: "Sumeru" },
  { name: "鹿野院平蔵",       icon: "Heizou.png",           element: "kaze",     nation: "Inazuma" },
  { name: "久岐忍",           icon: "KukiShinobu.png",      element: "kaminari", nation: "Inazuma" },
  { name: "夜蘭",             icon: "Yelan.png",            element: "mizu",     nation: "Liyue" },
  { name: "神里綾人",         icon: "KamisatoAyato.png",    element: "mizu",     nation: "Inazuma" },
  { name: "八重神子",         icon: "YaeMiko.png",          element: "kaminari", nation: "Inazuma" },
  { name: "雲菫",             icon: "YunJin.png",           element: "iwa",      nation: "Liyue" },
  { name: "申鶴",             icon: "Shenhe.png",           element: "koori",    nation: "Liyue" },
  { name: "荒瀧一斗",         icon: "AratakiItto.png",      element: "iwa",      nation: "Inazuma" },
  { name: "ゴロー",           icon: "Gorou.png",            element: "iwa",      nation: "Inazuma" },
  { name: "トーマ",           icon: "Thoma.png",            element: "hi",       nation: "Inazuma" },
  { name: "珊瑚宮心海",       icon: "Kokomi.png",           element: "mizu",     nation: "Inazuma" },
  { name: "九条裟羅",         icon: "KujouSara.png",        element: "kaminari", nation: "Inazuma" },
  { name: "雷電将軍",         icon: "Raiden.png",           element: "kaminari", nation: "Inazuma" },
  { name: "早柚",             icon: "Sayu.png",             element: "kaze",     nation: "Inazuma" },
  { name: "宵宮",             icon: "Yoimiya.png",          element: "hi",       nation: "Inazuma" },
  { name: "神里綾華",         icon: "AyakaKamisato.png",    element: "koori",    nation: "Inazuma" },
  { name: "楓原万葉",         icon: "KazuhaKaedehara.png",  element: "kaze",     nation: "Inazuma" },
  { name: "エウルア",         icon: "Eula.png",             element: "koori",    nation: "Mondstadt" },
  { name: "煙緋",             icon: "YanFei.png",           element: "hi",       nation: "Liyue" },
  { name: "ロサリア",         icon: "rosaria.png",          element: "koori",    nation: "Mondstadt" },
  { name: "胡桃",             icon: "Hutao.png",            element: "hi",       nation: "Liyue" },
  { name: "魈",               icon: "Xiao.png",             element: "kaze",     nation: "Liyue" },
  { name: "甘雨",             icon: "Ganyu.png",            element: "koori",    nation: "Liyue" },
  { name: "アルベド",         icon: "Albedo.png",           element: "iwa",      nation: "Mondstadt" },
  { name: "鍾離",             icon: "Zhongli.png",          element: "iwa",      nation: "Liyue" },
  { name: "辛炎",             icon: "Xinyan.png",           element: "hi",       nation: "Liyue" },
  { name: "タルタリヤ",       icon: "Tartaglia.png",        element: "mizu",     nation: "Snezhnaya" },
  { name: "ディオナ",         icon: "Diona.png",            element: "koori",    nation: "Mondstadt" },
  { name: "クレー",           icon: "Klee.png",             element: "hi",       nation: "Mondstadt" },
  { name: "七七",             icon: "Qiqi.png",             element: "koori",    nation: "Liyue" },
  { name: "刻晴",             icon: "Keqing.png",           element: "kaminari", nation: "Liyue" },
  { name: "凝光",             icon: "Ningguang.png",        element: "iwa",      nation: "Liyue" },
  { name: "香菱",             icon: "Xiangling.png",        element: "hi",       nation: "Liyue" },
  { name: "行秋",             icon: "Xingqiu.png",          element: "mizu",     nation: "Liyue" },
  { name: "重雲",             icon: "Chongyun.png",         element: "koori",    nation: "Liyue" },
  { name: "北斗",             icon: "Beidou.png",           element: "kaminari", nation: "Liyue" },
  { name: "ウェンティ",       icon: "Venti.png",            element: "kaze",     nation: "Mondstadt" },
  { name: "ディルック",       icon: "Diluc.png",            element: "hi",       nation: "Mondstadt" },
  { name: "モナ",             icon: "Mona.png",             element: "mizu",     nation: "Mondstadt" },
  { name: "ジン",             icon: "Jean.png",             element: "kaze",     nation: "Mondstadt" },
  { name: "レザー",           icon: "Razor.png",            element: "kaminari", nation: "Mondstadt" },
  { name: "ノエル",           icon: "Noelle.png",           element: "iwa",      nation: "Mondstadt" },
  { name: "バーバラ",         icon: "barbara.png",          element: "mizu",     nation: "Mondstadt" },
  { name: "フィッシュル",     icon: "Fischl.png",           element: "kaminari", nation: "Mondstadt" },
  { name: "ベネット",         icon: "Bennett.png",          element: "hi",       nation: "Mondstadt" },
  { name: "スクロース",       icon: "Sucrose.png",          element: "kaze",     nation: "Mondstadt" },
  { name: "リサ",             icon: "Lisa.png",             element: "kaminari", nation: "Mondstadt" },
  { name: "ガイア",           icon: "Kaeya.png",            element: "koori",    nation: "Mondstadt" },
  { name: "アンバー",         icon: "amber.png",            element: "hi",       nation: "Mondstadt" },
  { name: "ホタル",           icon: "hotaru.png",           element: null,       nation: null },
  { name: "ソラ",             icon: "sora.png",             element: null,       nation: null },
  { name: "アーロイ",         icon: "aroi.png",             element: "koori",    nation: null },
  { name: "パイモン",         icon: "paimon.png",           element: null,       nation: null },

];

// ===== バージョン画像データ (GenshinCheck用) =====
export const genshinVersions = [
  "7_0.png",
  "luna8.png",
  "luna7.png",
  "luna6.png",
  "luna5.png",
  "luna4.png",
  "luna3.png",
  "luna2.png",
  "luna1.png",
  "5_8.png",
  "5_7.png",
  "5_6.png",
  "5_5.png",
  "5_4.png",
  "5_3.png",
  "5_2.png",
  "5_1.png",
  "5_0.png",
  "4_8.png",
  "4_7.png",
  "4_6.png",
  "4_5.png",
  "4_4.png",
  "4_3.png",
  "4_2.png",
  "4_1.png",
  "4_0.png",
  "3_8.png",
  "3_7.png",
  "3_6.png",
  "3_5.png",
  "3_4.png",
  "3_3.png",
  "3_2.png",
  "3_1.png",
  "3_0.png",
  "2_8.png",
  "2_7.png",
  "2_6.png",
  "2_5.png",
  "2_4.png",
  "2_3.png",
  "2_2.png",
  "2_1.png",
  "2_0.png",
  "1_6.png",
  "1_5.png",
  "1_4.png",
  "1_3.png",
  "1_2.png",
  "1_1.png",
  "1_0.png",
];
